import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Input from "../components/Input";
import { Table, ToDo } from "../components/Table";
import { Typography } from "../dizzy/Typography";
import { useLocalStorage } from "../hooks/useLocalStorage";

const Home: NextPage = () => {
  const [serverSideTodos, setServerSideTodos] = useLocalStorage<ToDo[]>(
    "todos",
    []
  );
  const [clientSideTodos, setClientSideTodos] = useState<ToDo[]>([]);

  useEffect(() => {
    if (clientSideTodos.length === 0) {
      setClientSideTodos(serverSideTodos);
    }
  }, [serverSideTodos]);

  useEffect(() => {
    setServerSideTodos(clientSideTodos);
  }, [clientSideTodos, setServerSideTodos]);

  function handleDone(todo: ToDo) {
    setClientSideTodos(
      clientSideTodos.map((t) =>
        t.id === todo.id ? { ...t, completed: !t.completed } : t
      )
    );
  }

  function handleAdd(todo: ToDo) {
    setClientSideTodos([...clientSideTodos, todo]);
  }

  function deleteTodo(todo: ToDo) {
    setClientSideTodos(clientSideTodos.filter((t) => t.id !== todo.id));
  }

  return (
    <>
      <Head>
        <title>SSR Todos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/trashcan.svg" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4 sm:w-5/6">
        <Typography as="h1" color="orange600" size="xl">
          Todo App
        </Typography>
        <div className="container flex flex-col justify-evenly items-center mt-10">
          <Table
            todos={clientSideTodos}
            handleDone={handleDone}
            deleteTodo={deleteTodo}
          />
          <Input numTodos={clientSideTodos.length} addTodo={handleAdd} />
        </div>
      </main>
    </>
  );
};

export default Home;
